language: php

php:
  - 7.2
  - 7.3
  - 7.4

matrix:
  allow_failures:
    - php: 7.4

before_script:
  - composer selfupdate
  - composer install --dev --prefer-dist
  
notifications:
  email: false
