language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  allow_failures:
    - php: 7.4snapshot

before_script:
  - composer selfupdate
  - composer install --prefer-dist
  
notifications:
  email: false
